/**
 * OutputDocument.java
 *
 * This file was generated by MapForce 2018r2.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the MapForce Documentation for further details.
 * http://www.altova.com/mapforce
 */

package com.test.integration.spring.testspringcloudintegration.Mapping.Output;



import com.altova.text.tablelike.ColumnSpecification;
import com.altova.text.tablelike.Header;
import com.altova.text.tablelike.ISerializer;
import com.altova.text.tablelike.csv.Table;
import com.altova.text.tablelike.csv.Serializer;

public class OutputDocument extends Table
{
	protected ISerializer createSerializer()
	{
		Serializer result= new Serializer(this,0);
		result.getFormat().setAssumeFirstRowAsHeaders(false);
		result.getFormat().setFieldDelimiter(',');
		
		result.getFormat().setQuoteCharacter('\"');
		
		result.getFormat().setRemoveEmpty(true);
		result.getFormat().setAlwaysQuote(0 == 1);
		return result;
	}
	protected void initHeader(Header header)
	{
		
		header.add(new ColumnSpecification("Nome"));
	}
	public OutputDocument(com.altova.typeinfo.TypeInfo tableType,int lineend) {
        super( tableType,lineend);
    }
}



